# Generated by Django 4.1.7 on 2023-04-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_rename_bookmodel_book_rename_ordermodel_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='static/images/No_image_available.svg.png', upload_to=''),
        ),
    ]
