# Generated by Django 4.1.7 on 2023-04-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('success', 'success'), ('fail', 'fail')], default='in_work', max_length=20),
        ),
    ]
