# Generated by Django 4.1.7 on 2023-04-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_work', 'in_work'), ('ordered', 'ordered'), ('success', 'success'), ('fail', 'fail')], default='in_work', max_length=20),
        ),
    ]
