# Generated by Django 4.1.7 on 2023-04-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
    ]
