# Generated by Django 4.1.7 on 2023-04-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_remove_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='No_image_available.svg.png', null=True, upload_to=''),
        ),
    ]
