version: "3.11"

services:

  shop:
    build:
      context: .
      dockerfile: ./docker/shop/Dockerfile
    image: shop:0.0.1-dev
    container_name: shop
    command: bash docker/runserver.sh
    environment:
      - DB_HOST=shop_db
      - DB_PORT=5432
    depends_on:
      - shop_db
      - celery
    expose:
      - 8000
    networks:
      - shop_db_network
      - nginx_network
      - webnet
#    volumes:
#      - ./shop:/home/appuser/app

  store:
    build:
      context: .
      dockerfile: ./docker/store/Dockerfile
    image: store:0.0.1-dev
    container_name: store
    command: bash docker/runserver.sh
    environment:
      - DB_HOST=store_db
      - DB_PORT=5432
    depends_on:
      - store_db
    expose:
      - 8001
    networks:
      - store_db_network
      - nginx_network
#    volumes:
#      - ./store:/home/appuser/app

  shop_db:
    container_name: shop_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=shop_user
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - shop-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - shop_db_network

  store_db:
    container_name: store_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=shop_user
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - store-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - store_db_network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: on-failure
    networks:
      - nginx_network
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - shop
      - store
    healthcheck:
      test: ["CMD-SHELL", "ps ax", "|" ,"grep -v grep", "|" ,"grep nginx",  "||", "exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.0-alpine
    restart: on-failure
    networks:
      - webnet
    expose:
      - 4369
      - 5671
      - 5672
      - 15672
      - 25672
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 5s
      timeout: 15s
      retries: 1

  celery:
    container_name: celery
    image: celery
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "ps ax", "|" ,"grep -v grep", "|" ,"grep celery",  "||", "exit 1"]
      interval: 1m
      timeout: 5s
      retries: 2


networks:
  shop_db_network:
  store_db_network:
  nginx_network:
  webnet:

volumes:
  shop-db-data:
  store-db-data:
