version: '3'

networks:
  app_net:
    driver: bridge

services:
  db:
    image: postgres:15
    volumes:
      - ~/.pg/pg_data/yt:/var/lib/postgresql/data
    networks:
      - app_net
    env_file:
      - config/nginx/.env
  app:
    build:
      context: .
      dockerfile: docker/shop/Dockerfile
#    image: shop:latest
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    networks:
      - app_net
    depends_on:
      - db
    environment:
      DATABASE_PORT: '5432'
    env_file:
      - config/nginx/.env
    command: >
      bash -c "python3 manage.py migrate && python3 manage.py runserver"
#      - celery
#    environment:
#      - DJANGO_SETTINGS_MODULE=shop.shop.settings
#      - DEBUG=1
#      - SECRET_KEY=SECRET_KEY
#      - DATABASE_URL=postgresql://shop_user:mypassword@db:5432/shop_db
#      - CELERY_BROKER=amqp://guest:guest@localhost:5672/
#  api:
#    build:
#        context: .
#        dockerfile: store/Dockerfile
#    ports:
#      - '8001:8001'
#    volumes:
#      - .:/api
#    depends_on:
#      - db
#    environment:
#      - DJANGO_SETTINGS_MODULE=store.store.settings
#      - DEBUG=1
#      - SECRET_KEY=your-secret-key
#      - DATABASE_URL=postgres://shop_user:mypassword@db:5432/myproject
#  db:
#    image: postgres:15
#    container_name: postgres
#    env_file:
#      - .env
#    environment:
#      - POSTGRES_DB=myproject
#      - POSTGRES_USER=shop_user
#      - POSTGRES_PASSWORD=mypassword
#  celery:
#    build:
#      context: .
#      dockerfile: Dockerfile.celery
#    depends_on:
#      - db
#      - rabbitmq
#    environment:
#      - CELERY_BROKER_URL=amqp://guest:guest@localhost:5672/
#      - CELERY_RESULT_BACKEND=rpc://
#  rabbitmq:
#    image: rabbitmq:3.11-alpine
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
