# Generated by Django 4.1.7 on 2023-04-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('delivery_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('book_store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.book')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_app.bookitem')),
                ('order_item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_app.orderitem')),
            ],
        ),
    ]
