# Generated by Django 4.1.7 on 2023-04-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_deliveryaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_email',
        ),
    ]
