# Generated by Django 4.1.7 on 2023-04-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='user_id',
        ),
    ]
