# Generated by Django 4.1.7 on 2023-04-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_remove_deliveryaddress_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='No_image_available.svg.png', null=True, upload_to=''),
        ),
    ]
